<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Errors;


use Polar\Models\Errors;
use Polar\Utils;

class ResourceNotFound
{
    /**
     *
     * @var Error $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Errors\Error')]
    public Error $error;

    /**
     *
     * @var string $detail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('detail')]
    public string $detail;

    /**
     * @param  Error  $error
     * @param  string  $detail
     */
    public function __construct(string $detail, Error $error = Error::ResourceNotFound)
    {
        $this->error = $error;
        $this->detail = $detail;
    }

    public function toException(): ResourceNotFoundThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ResourceNotFoundThrowable($message, (int) $code, $this);
    }
}