<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Errors;


use Polar\Models\Errors;
use Polar\Utils;

class Unauthorized
{
    /**
     *
     * @var UnauthorizedError $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Errors\UnauthorizedError')]
    public UnauthorizedError $error;

    /**
     *
     * @var string $detail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('detail')]
    public string $detail;

    /**
     * @param  UnauthorizedError  $error
     * @param  string  $detail
     */
    public function __construct(string $detail, UnauthorizedError $error = UnauthorizedError::Unauthorized)
    {
        $this->error = $error;
        $this->detail = $detail;
    }

    public function toException(): UnauthorizedThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new UnauthorizedThrowable($message, (int) $code, $this);
    }
}