workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Polar-OAS:
        inputs:
            - location: https://api.polar.sh/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/type_parameter.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/product_price_discriminator.yml
            - location: https://raw.githubusercontent.com/polarsource/polar/main/sdk/overlays/read_only.yml
targets:
    polar:
        target: php
        source: Polar-OAS
        publish:
            packagist:
                username: polar
                token: $packagist_token
