<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Utils\SpeakeasyMetadata;
class CheckoutsCustomClientGetRequest
{
    /**
     * The checkout session client secret.
     *
     * @var string $clientSecret
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=client_secret')]
    public string $clientSecret;

    /**
     * @param  string  $clientSecret
     */
    public function __construct(string $clientSecret)
    {
        $this->clientSecret = $clientSecret;
    }
}