<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Operations;

use Polar\Models\Components;
use Polar\Utils\SpeakeasyMetadata;
class FilesUpdateRequest
{
    /**
     * The file ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var Components\FilePatch $filePatch
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\FilePatch $filePatch;

    /**
     * @param  string  $id
     * @param  Components\FilePatch  $filePatch
     */
    public function __construct(string $id, Components\FilePatch $filePatch)
    {
        $this->id = $id;
        $this->filePatch = $filePatch;
    }
}