<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class AdvertisementCampaign
{
    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $imageUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_url')]
    public string $imageUrl;

    /**
     *
     * @var string $text
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('text')]
    public string $text;

    /**
     *
     * @var string $linkUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('link_url')]
    public string $linkUrl;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?string $imageUrlDark
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_url_dark')]
    public ?string $imageUrlDark;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $imageUrl
     * @param  string  $text
     * @param  string  $linkUrl
     * @param  ?\DateTime  $modifiedAt
     * @param  ?string  $imageUrlDark
     */
    public function __construct(\DateTime $createdAt, string $id, string $imageUrl, string $text, string $linkUrl, ?\DateTime $modifiedAt = null, ?string $imageUrlDark = null)
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->imageUrl = $imageUrl;
        $this->text = $text;
        $this->linkUrl = $linkUrl;
        $this->modifiedAt = $modifiedAt;
        $this->imageUrlDark = $imageUrlDark;
    }
}