<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitLicenseKeysCreate
{
    /**
     * The description of the benefit. Will be displayed on products having this benefit.
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     *
     * @var BenefitLicenseKeysCreateProperties $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BenefitLicenseKeysCreateProperties')]
    public BenefitLicenseKeysCreateProperties $properties;

    /**
     * The ID of the organization owning the benefit. **Required unless you use an organization token.**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $organizationId = null;

    /**
     *
     * @var BenefitLicenseKeysCreateType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BenefitLicenseKeysCreateType')]
    public BenefitLicenseKeysCreateType $type;

    /**
     * @param  BenefitLicenseKeysCreateType  $type
     * @param  string  $description
     * @param  BenefitLicenseKeysCreateProperties  $properties
     * @param  ?string  $organizationId
     */
    public function __construct(string $description, BenefitLicenseKeysCreateProperties $properties, ?string $organizationId = null, BenefitLicenseKeysCreateType $type = BenefitLicenseKeysCreateType::LicenseKeys)
    {
        $this->description = $description;
        $this->properties = $properties;
        $this->organizationId = $organizationId;
        $this->type = $type;
    }
}