<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitGrantAdsProperties
{
    /**
     *
     * @var string $advertisementCampaignId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('advertisement_campaign_id')]
    public string $advertisementCampaignId;

    /**
     * @param  string  $advertisementCampaignId
     */
    public function __construct(string $advertisementCampaignId)
    {
        $this->advertisementCampaignId = $advertisementCampaignId;
    }
}