<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitDownloadablesCreateProperties
{
    /**
     * $files
     *
     * @var array<string> $files
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('files')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $files;

    /**
     * $archived
     *
     * @var ?array<string, bool> $archived
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('archived')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, bool>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $archived = null;

    /**
     * @param  array<string>  $files
     * @param  ?array<string, bool>  $archived
     */
    public function __construct(array $files, ?array $archived = null)
    {
        $this->files = $files;
        $this->archived = $archived;
    }
}