<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitLicenseKeyActivationProperties
{
    /**
     *
     * @var int $limit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('limit')]
    public int $limit;

    /**
     *
     * @var bool $enableCustomerAdmin
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enable_customer_admin')]
    public bool $enableCustomerAdmin;

    /**
     * @param  int  $limit
     * @param  bool  $enableCustomerAdmin
     */
    public function __construct(int $limit, bool $enableCustomerAdmin)
    {
        $this->limit = $limit;
        $this->enableCustomerAdmin = $enableCustomerAdmin;
    }
}