<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum BenefitGrantGitHubRepositoryPropertiesPermission: string
{
    case Pull = 'pull';
    case Triage = 'triage';
    case Push = 'push';
    case Maintain = 'maintain';
    case Admin = 'admin';
}
