<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class BenefitGrantGitHubRepositoryProperties
{
    /**
     *
     * @var ?string $accountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('account_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $accountId = null;

    /**
     *
     * @var ?string $repositoryOwner
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('repository_owner')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $repositoryOwner = null;

    /**
     *
     * @var ?string $repositoryName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('repository_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $repositoryName = null;

    /**
     *
     * @var ?BenefitGrantGitHubRepositoryPropertiesPermission $permission
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('permission')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BenefitGrantGitHubRepositoryPropertiesPermission|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BenefitGrantGitHubRepositoryPropertiesPermission $permission = null;

    /**
     * @param  ?string  $accountId
     * @param  ?string  $repositoryOwner
     * @param  ?string  $repositoryName
     * @param  ?BenefitGrantGitHubRepositoryPropertiesPermission  $permission
     */
    public function __construct(?string $accountId = null, ?string $repositoryOwner = null, ?string $repositoryName = null, ?BenefitGrantGitHubRepositoryPropertiesPermission $permission = null)
    {
        $this->accountId = $accountId;
        $this->repositoryOwner = $repositoryOwner;
        $this->repositoryName = $repositoryName;
        $this->permission = $permission;
    }
}