<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** BenefitAdsProperties - Properties for a benefit of type `ads`. */
class BenefitAdsProperties
{
    /**
     * The height of the displayed ad.
     *
     * @var ?int $imageHeight
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_height')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $imageHeight = null;

    /**
     * The width of the displayed ad.
     *
     * @var ?int $imageWidth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image_width')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $imageWidth = null;

    /**
     * @param  ?int  $imageHeight
     * @param  ?int  $imageWidth
     */
    public function __construct(?int $imageHeight = 400, ?int $imageWidth = 400)
    {
        $this->imageHeight = $imageHeight;
        $this->imageWidth = $imageWidth;
    }
}