<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CheckoutLinkPriceCreate
{
    /**
     * ID of the product price to checkout.
     *
     * @var string $productPriceId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('product_price_id')]
    public string $productPriceId;

    /**
     * Key-value object allowing you to store additional information.
     *
     *
     * The key must be a string with a maximum length of **40 characters**.
     * The value must be either:
     *
     * * A string with a maximum length of **500 characters**
     * * An integer
     * * A boolean
     *
     * You can store up to **50 key-value pairs**.
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * Optional label to distinguish links internally
     *
     * @var ?string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $label = null;

    /**
     * ID of the discount to apply to the checkout. If the discount is not applicable anymore when opening the checkout link, it'll be ignored.
     *
     * @var ?string $discountId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount_id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $discountId = null;

    /**
     * URL where the customer will be redirected after a successful payment.You can add the `checkout_id={CHECKOUT_ID}` query parameter to retrieve the checkout session id.
     *
     * @var ?string $successUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('success_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $successUrl = null;

    /**
     * Payment processor to use. Currently only Stripe is supported.
     *
     * @var CheckoutLinkPriceCreatePaymentProcessor $paymentProcessor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_processor')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CheckoutLinkPriceCreatePaymentProcessor')]
    public CheckoutLinkPriceCreatePaymentProcessor $paymentProcessor;

    /**
     * Whether to allow the customer to apply discount codes. If you apply a discount through `discount_id`, it'll still be applied, but the customer won't be able to change it.
     *
     * @var ?bool $allowDiscountCodes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allow_discount_codes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowDiscountCodes = null;

    /**
     * @param  CheckoutLinkPriceCreatePaymentProcessor  $paymentProcessor
     * @param  string  $productPriceId
     * @param  ?array<string, mixed>  $metadata
     * @param  ?bool  $allowDiscountCodes
     * @param  ?string  $label
     * @param  ?string  $discountId
     * @param  ?string  $successUrl
     */
    public function __construct(string $productPriceId, ?array $metadata = null, ?string $label = null, ?string $discountId = null, ?string $successUrl = null, CheckoutLinkPriceCreatePaymentProcessor $paymentProcessor = CheckoutLinkPriceCreatePaymentProcessor::Stripe, ?bool $allowDiscountCodes = true)
    {
        $this->productPriceId = $productPriceId;
        $this->metadata = $metadata;
        $this->label = $label;
        $this->discountId = $discountId;
        $this->successUrl = $successUrl;
        $this->paymentProcessor = $paymentProcessor;
        $this->allowDiscountCodes = $allowDiscountCodes;
    }
}