<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** CheckoutPublicCustomFieldData - Key-value object storing custom field values. */
class CheckoutPublicCustomFieldData
{

    public function __construct()
    {
    }
}