<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum CustomFieldUpdateCheckboxType: string
{
    case Checkbox = 'checkbox';
}
