<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum CustomFieldSortProperty: string
{
    case CreatedAt = 'created_at';
    case MinusCreatedAt = '-created_at';
    case Slug = 'slug';
    case MinusSlug = '-slug';
    case Name = 'name';
    case MinusName = '-name';
    case Type = 'type';
    case MinusType = '-type';
}
