<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** CustomFieldUpdateDate - Schema to update a custom field of type date. */
class CustomFieldUpdateDate
{
    /**
     * $metadata
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $slug = null;

    /**
     *
     * @var ?CustomFieldDateProperties $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CustomFieldDateProperties|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CustomFieldDateProperties $properties = null;

    /**
     *
     * @var CustomFieldUpdateDateType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CustomFieldUpdateDateType')]
    public CustomFieldUpdateDateType $type;

    /**
     * @param  CustomFieldUpdateDateType  $type
     * @param  ?array<string, mixed>  $metadata
     * @param  ?string  $name
     * @param  ?string  $slug
     * @param  ?CustomFieldDateProperties  $properties
     */
    public function __construct(?array $metadata = null, ?string $name = null, ?string $slug = null, ?CustomFieldDateProperties $properties = null, CustomFieldUpdateDateType $type = CustomFieldUpdateDateType::Date)
    {
        $this->metadata = $metadata;
        $this->name = $name;
        $this->slug = $slug;
        $this->properties = $properties;
        $this->type = $type;
    }
}