<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class CustomerBenefitGrantAdsUpdate
{
    /**
     *
     * @var CustomerBenefitGrantAdsUpdateBenefitType $benefitType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CustomerBenefitGrantAdsUpdateBenefitType')]
    public CustomerBenefitGrantAdsUpdateBenefitType $benefitType;

    /**
     * @param  CustomerBenefitGrantAdsUpdateBenefitType  $benefitType
     */
    public function __construct(CustomerBenefitGrantAdsUpdateBenefitType $benefitType = CustomerBenefitGrantAdsUpdateBenefitType::Ads)
    {
        $this->benefitType = $benefitType;
    }
}