<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** DiscountUpdate - Schema to update a discount. */
class DiscountUpdate
{
    /**
     * $metadata
     *
     * @var ?array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $code
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $code = null;

    /**
     *
     * @var ?\DateTime $startsAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('starts_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $startsAt = null;

    /**
     *
     * @var ?\DateTime $endsAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ends_at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $endsAt = null;

    /**
     *
     * @var ?int $maxRedemptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('max_redemptions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $maxRedemptions = null;

    /**
     *
     * @var ?DiscountDuration $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\DiscountDuration|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DiscountDuration $duration = null;

    /**
     *
     * @var ?int $durationInMonths
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration_in_months')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $durationInMonths = null;

    /**
     *
     * @var ?DiscountType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\DiscountType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DiscountType $type = null;

    /**
     *
     * @var ?int $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $amount = null;

    /**
     *
     * @var ?int $basisPoints
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('basis_points')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $basisPoints = null;

    /**
     * $products
     *
     * @var ?array<string> $products
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('products')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $products = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * @param  ?array<string, mixed>  $metadata
     * @param  ?string  $name
     * @param  ?string  $code
     * @param  ?\DateTime  $startsAt
     * @param  ?\DateTime  $endsAt
     * @param  ?int  $maxRedemptions
     * @param  ?DiscountDuration  $duration
     * @param  ?int  $durationInMonths
     * @param  ?DiscountType  $type
     * @param  ?int  $amount
     * @param  ?string  $currency
     * @param  ?int  $basisPoints
     * @param  ?array<string>  $products
     */
    public function __construct(?array $metadata = null, ?string $name = null, ?string $code = null, ?\DateTime $startsAt = null, ?\DateTime $endsAt = null, ?int $maxRedemptions = null, ?DiscountDuration $duration = null, ?int $durationInMonths = null, ?DiscountType $type = null, ?int $amount = null, ?int $basisPoints = null, ?array $products = null, ?string $currency = 'usd')
    {
        $this->metadata = $metadata;
        $this->name = $name;
        $this->code = $code;
        $this->startsAt = $startsAt;
        $this->endsAt = $endsAt;
        $this->maxRedemptions = $maxRedemptions;
        $this->duration = $duration;
        $this->durationInMonths = $durationInMonths;
        $this->type = $type;
        $this->amount = $amount;
        $this->basisPoints = $basisPoints;
        $this->products = $products;
        $this->currency = $currency;
    }
}