<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum DiscountDuration: string
{
    case Once = 'once';
    case Forever = 'forever';
    case Repeating = 'repeating';
}
