<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class ExternalOrganization
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    public string $avatarUrl;

    /**
     *
     * @var bool $isPersonal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('is_personal')]
    public bool $isPersonal;

    /**
     *
     * @var ?string $bio
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bio')]
    public ?string $bio;

    /**
     *
     * @var ?string $prettyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pretty_name')]
    public ?string $prettyName;

    /**
     *
     * @var ?string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    public ?string $company;

    /**
     *
     * @var ?string $blog
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blog')]
    public ?string $blog;

    /**
     *
     * @var ?string $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    public ?string $location;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     *
     * @var ?string $twitterUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('twitter_username')]
    public ?string $twitterUsername;

    /**
     *
     * @var ?string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public ?string $organizationId;

    /**
     *
     * @var Platforms $platform
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platform')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Platforms')]
    public Platforms $platform;

    /**
     * @param  string  $id
     * @param  Platforms  $platform
     * @param  string  $name
     * @param  string  $avatarUrl
     * @param  bool  $isPersonal
     * @param  ?string  $bio
     * @param  ?string  $prettyName
     * @param  ?string  $company
     * @param  ?string  $blog
     * @param  ?string  $location
     * @param  ?string  $email
     * @param  ?string  $twitterUsername
     * @param  ?string  $organizationId
     */
    public function __construct(string $id, string $name, string $avatarUrl, bool $isPersonal, ?string $bio = null, ?string $prettyName = null, ?string $company = null, ?string $blog = null, ?string $location = null, ?string $email = null, ?string $twitterUsername = null, ?string $organizationId = null, Platforms $platform = Platforms::Github)
    {
        $this->id = $id;
        $this->name = $name;
        $this->avatarUrl = $avatarUrl;
        $this->isPersonal = $isPersonal;
        $this->bio = $bio;
        $this->prettyName = $prettyName;
        $this->company = $company;
        $this->blog = $blog;
        $this->location = $location;
        $this->email = $email;
        $this->twitterUsername = $twitterUsername;
        $this->organizationId = $organizationId;
        $this->platform = $platform;
    }
}