<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class FileUploadCompleted
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * $parts
     *
     * @var array<S3FileUploadCompletedPart> $parts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('parts')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\S3FileUploadCompletedPart>')]
    public array $parts;

    /**
     * @param  string  $id
     * @param  string  $path
     * @param  array<S3FileUploadCompletedPart>  $parts
     */
    public function __construct(string $id, string $path, array $parts)
    {
        $this->id = $id;
        $this->path = $path;
        $this->parts = $parts;
    }
}