<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Funding
{
    /**
     *
     * @var ?CurrencyAmount $fundingGoal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('funding_goal')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CurrencyAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyAmount $fundingGoal = null;

    /**
     * Sum of pledges to this isuse (including currently open pledges and pledges that have been paid out). Always in USD.
     *
     * @var ?CurrencyAmount $pledgesSum
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pledges_sum')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\CurrencyAmount|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?CurrencyAmount $pledgesSum = null;

    /**
     * @param  ?CurrencyAmount  $fundingGoal
     * @param  ?CurrencyAmount  $pledgesSum
     */
    public function __construct(?CurrencyAmount $fundingGoal = null, ?CurrencyAmount $pledgesSum = null)
    {
        $this->fundingGoal = $fundingGoal;
        $this->pledgesSum = $pledgesSum;
    }
}