<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class LicenseKeyActivationBase
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $licenseKeyId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('license_key_id')]
    public string $licenseKeyId;

    /**
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     *
     * @var Meta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Meta')]
    public Meta $meta;

    /**
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * @param  string  $id
     * @param  string  $licenseKeyId
     * @param  string  $label
     * @param  Meta  $meta
     * @param  \DateTime  $createdAt
     * @param  ?\DateTime  $modifiedAt
     */
    public function __construct(string $id, string $licenseKeyId, string $label, Meta $meta, \DateTime $createdAt, ?\DateTime $modifiedAt = null)
    {
        $this->id = $id;
        $this->licenseKeyId = $licenseKeyId;
        $this->label = $label;
        $this->meta = $meta;
        $this->createdAt = $createdAt;
        $this->modifiedAt = $modifiedAt;
    }
}