<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class LicenseKeyActivate
{
    /**
     *
     * @var string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     *
     * @var string $organizationId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_id')]
    public string $organizationId;

    /**
     *
     * @var string $label
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('label')]
    public string $label;

    /**
     *
     * @var ?LicenseKeyActivateConditions $conditions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conditions')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\LicenseKeyActivateConditions|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LicenseKeyActivateConditions $conditions = null;

    /**
     *
     * @var ?LicenseKeyActivateMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\LicenseKeyActivateMeta|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LicenseKeyActivateMeta $meta = null;

    /**
     * @param  string  $key
     * @param  string  $organizationId
     * @param  string  $label
     * @param  ?LicenseKeyActivateConditions  $conditions
     * @param  ?LicenseKeyActivateMeta  $meta
     */
    public function __construct(string $key, string $organizationId, string $label, ?LicenseKeyActivateConditions $conditions = null, ?LicenseKeyActivateMeta $meta = null)
    {
        $this->key = $key;
        $this->organizationId = $organizationId;
        $this->label = $label;
        $this->conditions = $conditions;
        $this->meta = $meta;
    }
}