<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class LicenseKeyUser
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     *
     * @var string $publicName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('public_name')]
    public string $publicName;

    /**
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $avatarUrl = null;

    /**
     * @param  string  $id
     * @param  string  $email
     * @param  string  $publicName
     * @param  ?string  $avatarUrl
     */
    public function __construct(string $id, string $email, string $publicName, ?string $avatarUrl = null)
    {
        $this->id = $id;
        $this->email = $email;
        $this->publicName = $publicName;
        $this->avatarUrl = $avatarUrl;
    }
}