<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** MetricsResponse - Metrics response schema. */
class MetricsResponse
{
    /**
     * List of data for each timestamp.
     *
     * @var array<MetricPeriod> $periods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periods')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Polar\Models\Components\MetricPeriod>')]
    public array $periods;

    /**
     *
     * @var Metrics $metrics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metrics')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Metrics')]
    public Metrics $metrics;

    /**
     * @param  array<MetricPeriod>  $periods
     * @param  Metrics  $metrics
     */
    public function __construct(array $periods, Metrics $metrics)
    {
        $this->periods = $periods;
        $this->metrics = $metrics;
    }
}