<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class MetricPeriod
{
    /**
     * Timestamp of this period data.
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var int $orders
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('orders')]
    public int $orders;

    /**
     *
     * @var int $revenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('revenue')]
    public int $revenue;

    /**
     *
     * @var int $averageOrderValue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('average_order_value')]
    public int $averageOrderValue;

    /**
     *
     * @var int $oneTimeProducts
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products')]
    public int $oneTimeProducts;

    /**
     *
     * @var int $oneTimeProductsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('one_time_products_revenue')]
    public int $oneTimeProductsRevenue;

    /**
     *
     * @var int $newSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions')]
    public int $newSubscriptions;

    /**
     *
     * @var int $newSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('new_subscriptions_revenue')]
    public int $newSubscriptionsRevenue;

    /**
     *
     * @var int $renewedSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions')]
    public int $renewedSubscriptions;

    /**
     *
     * @var int $renewedSubscriptionsRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('renewed_subscriptions_revenue')]
    public int $renewedSubscriptionsRevenue;

    /**
     *
     * @var int $activeSubscriptions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active_subscriptions')]
    public int $activeSubscriptions;

    /**
     *
     * @var int $monthlyRecurringRevenue
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('monthly_recurring_revenue')]
    public int $monthlyRecurringRevenue;

    /**
     * @param  \DateTime  $timestamp
     * @param  int  $orders
     * @param  int  $revenue
     * @param  int  $averageOrderValue
     * @param  int  $oneTimeProducts
     * @param  int  $oneTimeProductsRevenue
     * @param  int  $newSubscriptions
     * @param  int  $newSubscriptionsRevenue
     * @param  int  $renewedSubscriptions
     * @param  int  $renewedSubscriptionsRevenue
     * @param  int  $activeSubscriptions
     * @param  int  $monthlyRecurringRevenue
     */
    public function __construct(\DateTime $timestamp, int $orders, int $revenue, int $averageOrderValue, int $oneTimeProducts, int $oneTimeProductsRevenue, int $newSubscriptions, int $newSubscriptionsRevenue, int $renewedSubscriptions, int $renewedSubscriptionsRevenue, int $activeSubscriptions, int $monthlyRecurringRevenue)
    {
        $this->timestamp = $timestamp;
        $this->orders = $orders;
        $this->revenue = $revenue;
        $this->averageOrderValue = $averageOrderValue;
        $this->oneTimeProducts = $oneTimeProducts;
        $this->oneTimeProductsRevenue = $oneTimeProductsRevenue;
        $this->newSubscriptions = $newSubscriptions;
        $this->newSubscriptionsRevenue = $newSubscriptionsRevenue;
        $this->renewedSubscriptions = $renewedSubscriptions;
        $this->renewedSubscriptionsRevenue = $renewedSubscriptionsRevenue;
        $this->activeSubscriptions = $activeSubscriptions;
        $this->monthlyRecurringRevenue = $monthlyRecurringRevenue;
    }
}