<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Organization
{
    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The organization ID.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     *
     * @var int $pledgeMinimumAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pledge_minimum_amount')]
    public int $pledgeMinimumAmount;

    /**
     *
     * @var bool $pledgeBadgeShowAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pledge_badge_show_amount')]
    public bool $pledgeBadgeShowAmount;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    public ?string $avatarUrl;

    /**
     *
     * @var ?string $bio
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bio')]
    public ?string $bio;

    /**
     *
     * @var ?string $company
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('company')]
    public ?string $company;

    /**
     *
     * @var ?string $blog
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('blog')]
    public ?string $blog;

    /**
     *
     * @var ?string $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    public ?string $location;

    /**
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     *
     * @var ?string $twitterUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('twitter_username')]
    public ?string $twitterUsername;

    /**
     *
     * @var ?int $defaultUpfrontSplitToContributors
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('default_upfront_split_to_contributors')]
    public ?int $defaultUpfrontSplitToContributors;

    /**
     * Settings for the organization profile
     *
     * @var ?OrganizationProfileSettings $profileSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('profile_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrganizationProfileSettings|null')]
    public ?OrganizationProfileSettings $profileSettings;

    /**
     * Settings for the organization features
     *
     * @var ?OrganizationFeatureSettings $featureSettings
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('feature_settings')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\OrganizationFeatureSettings|null')]
    public ?OrganizationFeatureSettings $featureSettings;

    /**
     * @param  \DateTime  $createdAt
     * @param  string  $id
     * @param  string  $name
     * @param  string  $slug
     * @param  int  $pledgeMinimumAmount
     * @param  bool  $pledgeBadgeShowAmount
     * @param  ?\DateTime  $modifiedAt
     * @param  ?string  $avatarUrl
     * @param  ?string  $bio
     * @param  ?string  $company
     * @param  ?string  $blog
     * @param  ?string  $location
     * @param  ?string  $email
     * @param  ?string  $twitterUsername
     * @param  ?int  $defaultUpfrontSplitToContributors
     * @param  ?OrganizationProfileSettings  $profileSettings
     * @param  ?OrganizationFeatureSettings  $featureSettings
     */
    public function __construct(\DateTime $createdAt, string $id, string $name, string $slug, int $pledgeMinimumAmount, bool $pledgeBadgeShowAmount, ?\DateTime $modifiedAt = null, ?string $avatarUrl = null, ?string $bio = null, ?string $company = null, ?string $blog = null, ?string $location = null, ?string $email = null, ?string $twitterUsername = null, ?int $defaultUpfrontSplitToContributors = null, ?OrganizationProfileSettings $profileSettings = null, ?OrganizationFeatureSettings $featureSettings = null)
    {
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->name = $name;
        $this->slug = $slug;
        $this->pledgeMinimumAmount = $pledgeMinimumAmount;
        $this->pledgeBadgeShowAmount = $pledgeBadgeShowAmount;
        $this->modifiedAt = $modifiedAt;
        $this->avatarUrl = $avatarUrl;
        $this->bio = $bio;
        $this->company = $company;
        $this->blog = $blog;
        $this->location = $location;
        $this->email = $email;
        $this->twitterUsername = $twitterUsername;
        $this->defaultUpfrontSplitToContributors = $defaultUpfrontSplitToContributors;
        $this->profileSettings = $profileSettings;
        $this->featureSettings = $featureSettings;
    }
}