<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class Pledger
{
    /**
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     *
     * @var ?string $githubUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('github_username')]
    public ?string $githubUsername;

    /**
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatar_url')]
    public ?string $avatarUrl;

    /**
     * @param  string  $name
     * @param  ?string  $githubUsername
     * @param  ?string  $avatarUrl
     */
    public function __construct(string $name, ?string $githubUsername = null, ?string $avatarUrl = null)
    {
        $this->name = $name;
        $this->githubUsername = $githubUsername;
        $this->avatarUrl = $avatarUrl;
    }
}