<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum PledgeType: string
{
    case PayUpfront = 'pay_upfront';
    case PayOnCompletion = 'pay_on_completion';
    case PayDirectly = 'pay_directly';
}
