<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** ProductPriceRecurringFreeCreate - Schema to create a free recurring product price, i.e. a subscription. */
class ProductPriceRecurringFreeCreate
{
    /**
     *
     * @var SubscriptionRecurringInterval $recurringInterval
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring_interval')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\SubscriptionRecurringInterval')]
    public SubscriptionRecurringInterval $recurringInterval;

    /**
     *
     * @var ProductPriceRecurringFreeCreateType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\ProductPriceRecurringFreeCreateType')]
    public ProductPriceRecurringFreeCreateType $type;

    /**
     *
     * @var ProductPriceRecurringFreeCreateAmountType $amountType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\ProductPriceRecurringFreeCreateAmountType')]
    public ProductPriceRecurringFreeCreateAmountType $amountType;

    /**
     * @param  ProductPriceRecurringFreeCreateType  $type
     * @param  ProductPriceRecurringFreeCreateAmountType  $amountType
     * @param  SubscriptionRecurringInterval  $recurringInterval
     */
    public function __construct(SubscriptionRecurringInterval $recurringInterval, ProductPriceRecurringFreeCreateType $type = ProductPriceRecurringFreeCreateType::Recurring, ProductPriceRecurringFreeCreateAmountType $amountType = ProductPriceRecurringFreeCreateAmountType::Free)
    {
        $this->recurringInterval = $recurringInterval;
        $this->type = $type;
        $this->amountType = $amountType;
    }
}