<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/** The type of the price. */
enum ProductPriceOneTimeFreeType: string
{
    case OneTime = 'one_time';
}
