<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class RepositoryProfileSettingsUpdate
{
    /**
     *
     * @var ?bool $setDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('set_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $setDescription = null;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     *
     * @var ?bool $setCoverImageUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('set_cover_image_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $setCoverImageUrl = null;

    /**
     *
     * @var ?string $coverImageUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cover_image_url')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $coverImageUrl = null;

    /**
     * $featuredOrganizations
     *
     * @var ?array<string> $featuredOrganizations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('featured_organizations')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $featuredOrganizations = null;

    /**
     * $highlightedSubscriptionTiers
     *
     * @var ?array<string> $highlightedSubscriptionTiers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('highlighted_subscription_tiers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $highlightedSubscriptionTiers = null;

    /**
     * $links
     *
     * @var ?array<string> $links
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('links')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $links = null;

    /**
     * @param  ?bool  $setDescription
     * @param  ?string  $description
     * @param  ?bool  $setCoverImageUrl
     * @param  ?string  $coverImageUrl
     * @param  ?array<string>  $featuredOrganizations
     * @param  ?array<string>  $highlightedSubscriptionTiers
     * @param  ?array<string>  $links
     */
    public function __construct(?bool $setDescription = null, ?string $description = null, ?bool $setCoverImageUrl = null, ?string $coverImageUrl = null, ?array $featuredOrganizations = null, ?array $highlightedSubscriptionTiers = null, ?array $links = null)
    {
        $this->setDescription = $setDescription;
        $this->description = $description;
        $this->setCoverImageUrl = $setCoverImageUrl;
        $this->coverImageUrl = $coverImageUrl;
        $this->featuredOrganizations = $featuredOrganizations;
        $this->highlightedSubscriptionTiers = $highlightedSubscriptionTiers;
        $this->links = $links;
    }
}