<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class S3FileUploadPart
{
    /**
     *
     * @var int $number
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('number')]
    public int $number;

    /**
     *
     * @var int $chunkStart
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('chunk_start')]
    public int $chunkStart;

    /**
     *
     * @var int $chunkEnd
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('chunk_end')]
    public int $chunkEnd;

    /**
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     *
     * @var \DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_at')]
    public \DateTime $expiresAt;

    /**
     * $headers
     *
     * @var ?array<string, string> $headers
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('headers')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $headers = null;

    /**
     *
     * @var ?string $checksumSha256Base64
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checksum_sha256_base64')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $checksumSha256Base64 = null;

    /**
     * @param  int  $number
     * @param  int  $chunkStart
     * @param  int  $chunkEnd
     * @param  string  $url
     * @param  \DateTime  $expiresAt
     * @param  ?array<string, string>  $headers
     * @param  ?string  $checksumSha256Base64
     */
    public function __construct(int $number, int $chunkStart, int $chunkEnd, string $url, \DateTime $expiresAt, ?string $checksumSha256Base64 = null, ?array $headers = null)
    {
        $this->number = $number;
        $this->chunkStart = $chunkStart;
        $this->chunkEnd = $chunkEnd;
        $this->url = $url;
        $this->expiresAt = $expiresAt;
        $this->headers = $headers;
        $this->checksumSha256Base64 = $checksumSha256Base64;
    }
}