<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum SubscriptionSortProperty: string
{
    case Customer = 'customer';
    case MinusCustomer = '-customer';
    case Status = 'status';
    case MinusStatus = '-status';
    case StartedAt = 'started_at';
    case MinusStartedAt = '-started_at';
    case CurrentPeriodEnd = 'current_period_end';
    case MinusCurrentPeriodEnd = '-current_period_end';
    case Amount = 'amount';
    case MinusAmount = '-amount';
    case Product = 'product';
    case MinusProduct = '-product';
    case Discount = 'discount';
    case MinusDiscount = '-discount';
}
