<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * List of supported tax ID formats.
 *
 *
 * Ref: https://docs.stripe.com/billing/customer/tax-ids#supported-tax-id
 */
enum TaxIDFormat: string
{
    case AdNrt = 'ad_nrt';
    case AeTrn = 'ae_trn';
    case ArCuit = 'ar_cuit';
    case AuAbn = 'au_abn';
    case AuArn = 'au_arn';
    case BgUic = 'bg_uic';
    case BhVat = 'bh_vat';
    case BoTin = 'bo_tin';
    case BrCnpj = 'br_cnpj';
    case BrCpf = 'br_cpf';
    case CaBn = 'ca_bn';
    case CaGstHst = 'ca_gst_hst';
    case CaPstBc = 'ca_pst_bc';
    case CaPstMb = 'ca_pst_mb';
    case CaPstSk = 'ca_pst_sk';
    case CaQst = 'ca_qst';
    case ChUid = 'ch_uid';
    case ChVat = 'ch_vat';
    case ClTin = 'cl_tin';
    case CnTin = 'cn_tin';
    case CoNit = 'co_nit';
    case CrTin = 'cr_tin';
    case DeStn = 'de_stn';
    case DoRcn = 'do_rcn';
    case EcRuc = 'ec_ruc';
    case EgTin = 'eg_tin';
    case EsCif = 'es_cif';
    case EuOssVat = 'eu_oss_vat';
    case EuVat = 'eu_vat';
    case GbVat = 'gb_vat';
    case GeVat = 'ge_vat';
    case HkBr = 'hk_br';
    case HrOib = 'hr_oib';
    case HuTin = 'hu_tin';
    case IdNpwp = 'id_npwp';
    case IlVat = 'il_vat';
    case InGst = 'in_gst';
    case IsVat = 'is_vat';
    case JpCn = 'jp_cn';
    case JpRn = 'jp_rn';
    case JpTrn = 'jp_trn';
    case KePin = 'ke_pin';
    case KrBrn = 'kr_brn';
    case KzBin = 'kz_bin';
    case LiUid = 'li_uid';
    case MxRfc = 'mx_rfc';
    case MyFrp = 'my_frp';
    case MyItn = 'my_itn';
    case MySst = 'my_sst';
    case NgTin = 'ng_tin';
    case NoVat = 'no_vat';
    case NoVoec = 'no_voec';
    case NzGst = 'nz_gst';
    case OmVat = 'om_vat';
    case PeRuc = 'pe_ruc';
    case PhTin = 'ph_tin';
    case RoTin = 'ro_tin';
    case RsPib = 'rs_pib';
    case RuInn = 'ru_inn';
    case RuKpp = 'ru_kpp';
    case SaVat = 'sa_vat';
    case SgGst = 'sg_gst';
    case SgUen = 'sg_uen';
    case SiTin = 'si_tin';
    case SvNit = 'sv_nit';
    case ThVat = 'th_vat';
    case TrTin = 'tr_tin';
    case TwVat = 'tw_vat';
    case UaVat = 'ua_vat';
    case UsEin = 'us_ein';
    case UyRuc = 'uy_ruc';
    case VeRif = 've_rif';
    case VnTin = 'vn_tin';
    case ZaVat = 'za_vat';
}
