<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum Timeframe: string
{
    case Year = 'year';
    case Month = 'month';
    case Day = 'day';
}
