<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


class ValidationError
{
    /**
     * $loc
     *
     * @var array<mixed> $loc
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('loc')]
    #[\Speakeasy\Serializer\Annotation\Type('array<mixed>')]
    public array $loc;

    /**
     *
     * @var string $msg
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('msg')]
    public string $msg;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  array<mixed>  $loc
     * @param  string  $msg
     * @param  string  $type
     */
    public function __construct(array $loc, string $msg, string $type)
    {
        $this->loc = $loc;
        $this->msg = $msg;
        $this->type = $type;
    }
}