<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookBenefitGrantRevokedPayload - Sent when a new benefit grant is revoked.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookBenefitGrantRevokedPayload
{
    /**
     *
     * @var BenefitGrantWebhook $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BenefitGrantWebhook')]
    public BenefitGrantWebhook $data;

    /**
     *
     * @var WebhookBenefitGrantRevokedPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\WebhookBenefitGrantRevokedPayloadType')]
    public WebhookBenefitGrantRevokedPayloadType $type;

    /**
     * @param  WebhookBenefitGrantRevokedPayloadType  $type
     * @param  BenefitGrantWebhook  $data
     */
    public function __construct(BenefitGrantWebhook $data, WebhookBenefitGrantRevokedPayloadType $type = WebhookBenefitGrantRevokedPayloadType::BenefitGrantRevoked)
    {
        $this->data = $data;
        $this->type = $type;
    }
}