<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


enum WebhookCheckoutUpdatedPayloadType: string
{
    case CheckoutUpdated = 'checkout.updated';
}
