<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookSubscriptionRevokedPayload - Sent when a subscription is revoked, the user looses access immediately.
 *
 * Happens when the subscription is canceled, or payment is past due.
 *
 * **Discord & Slack support:** Full
 */
class WebhookSubscriptionRevokedPayload
{
    /**
     *
     * @var Subscription $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Subscription')]
    public Subscription $data;

    /**
     *
     * @var WebhookSubscriptionRevokedPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\WebhookSubscriptionRevokedPayloadType')]
    public WebhookSubscriptionRevokedPayloadType $type;

    /**
     * @param  WebhookSubscriptionRevokedPayloadType  $type
     * @param  Subscription  $data
     */
    public function __construct(Subscription $data, WebhookSubscriptionRevokedPayloadType $type = WebhookSubscriptionRevokedPayloadType::SubscriptionRevoked)
    {
        $this->data = $data;
        $this->type = $type;
    }
}