<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookOrganizationUpdatedPayload - Sent when a organization is updated.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookOrganizationUpdatedPayload
{
    /**
     *
     * @var Organization $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Organization')]
    public Organization $data;

    /**
     *
     * @var WebhookOrganizationUpdatedPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\WebhookOrganizationUpdatedPayloadType')]
    public WebhookOrganizationUpdatedPayloadType $type;

    /**
     * @param  WebhookOrganizationUpdatedPayloadType  $type
     * @param  Organization  $data
     */
    public function __construct(Organization $data, WebhookOrganizationUpdatedPayloadType $type = WebhookOrganizationUpdatedPayloadType::OrganizationUpdated)
    {
        $this->data = $data;
        $this->type = $type;
    }
}