<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookOrderCreatedPayload - Sent when a new order is created.
 *
 *
 * **Discord & Slack support:** Full
 */
class WebhookOrderCreatedPayload
{
    /**
     *
     * @var Order $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\Order')]
    public Order $data;

    /**
     *
     * @var WebhookOrderCreatedPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\WebhookOrderCreatedPayloadType')]
    public WebhookOrderCreatedPayloadType $type;

    /**
     * @param  WebhookOrderCreatedPayloadType  $type
     * @param  Order  $data
     */
    public function __construct(Order $data, WebhookOrderCreatedPayloadType $type = WebhookOrderCreatedPayloadType::OrderCreated)
    {
        $this->data = $data;
        $this->type = $type;
    }
}