<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Polar\Models\Components;


/**
 * WebhookBenefitCreatedPayload - Sent when a new benefit is created.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookBenefitCreatedPayload
{
    /**
     *
     * @var BenefitAds|BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\BenefitAds|\Polar\Models\Components\BenefitCustom|\Polar\Models\Components\BenefitDiscord|\Polar\Models\Components\BenefitGitHubRepository|\Polar\Models\Components\BenefitDownloadables|\Polar\Models\Components\BenefitLicenseKeys')]
    public BenefitAds|BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys $data;

    /**
     *
     * @var WebhookBenefitCreatedPayloadType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Polar\Models\Components\WebhookBenefitCreatedPayloadType')]
    public WebhookBenefitCreatedPayloadType $type;

    /**
     * @param  WebhookBenefitCreatedPayloadType  $type
     * @param  BenefitAds|BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys  $data
     */
    public function __construct(BenefitAds|BenefitCustom|BenefitDiscord|BenefitGitHubRepository|BenefitDownloadables|BenefitLicenseKeys $data, WebhookBenefitCreatedPayloadType $type = WebhookBenefitCreatedPayloadType::BenefitCreated)
    {
        $this->data = $data;
        $this->type = $type;
    }
}